complete module 1
Dmitrii98/angular-module-1 pull request #1
Opened 2023-02-02 17:55 UTC by Dmitrii98

2023-02-05 20:54 UTC, parabolabam requested changes
It looks good overall. I'd like you to see a couple of things that are being applied can send your readability to space without a jet 👍

2023-02-05 20:54 UTC, parabolabam commented on src/app/app.component.ts
> +    this.charactersResults$ = this.searchTermByCharacters
you can avoid creating million of methods and their chains just to create an observable. You can simply define it as a class property.

```suggestion
    export class AppComponent {
      private readonly charactersResults$: Observable<any> = 
         this.searchTermByCharacters.pipe(
            map(characters => (characters ? characters.trim() : "")),
            filter(inputValue => inputValue.length >= 3),
            debounceTime(500),
            switchMap(inputValue => this.mockDataService.getCharacters(inputValue)),
        );
    }
```

In that case it would be much easier because you'll have to write much less code.

Also it's always better to avoid `any` type at any cost, because it neglects typescript as a tool. Using any means no need in typescript, from my POV

2023-02-05 20:54 UTC, parabolabam commented on src/app/app.component.ts
> +      this.isLoading = this.areAllValuesTrue([charactersLoading, planetsLoading]);
try to turn this.isLoading property into a stream as well, avoiding subscribing inside of a method. It will deteriorate testing completely

2023-02-05 20:54 UTC, parabolabam commented on src/app/app.component.ts
> +        this.charactersResults$,
I don't see charactersResults$ is a subscription. It's rather observable.
Same with second param. Corect me if I'm wrong

2023-02-05 20:54 UTC, parabolabam commented on src/app/app.component.ts
> +  areAllValuesTrue(elements: boolean[]): boolean {
It looks private to me, is it?

2023-02-05 20:54 UTC, parabolabam commented on src/app/app.component.ts
> +  charactersResults$: Observable<any>;
any type should be avoided at any cost :)

2023-02-06 09:07 UTC, Dmitrii98 commented on src/app/app.component.ts
> +        this.charactersResults$,
that's what I was confused about, I see that here is subscription but don't get how to unsubscribe that 

<img width="685" alt="image" src="https://user-images.githubusercontent.com/36797396/216930384-1679b536-45ef-4aac-9314-e2a52f1fd41c.png">

2023-02-06 09:10 UTC, Dmitrii98 commented on src/app/app.component.ts
> +  charactersResults$: Observable<any>;
this code was written in the original file, the task wasn't about fixing types but writing methods
please, correct me if I'm wrong

2023-02-06 09:11 UTC, Dmitrii98 commented on src/app/app.component.ts
> +      this.isLoading = this.areAllValuesTrue([charactersLoading, planetsLoading]);
Could you elaborate on that? didn't get the point

2023-02-06 09:11 UTC, Dmitrii98 commented on src/app/app.component.ts
> +    this.charactersResults$ = this.searchTermByCharacters
moved to a class property 

about any:
this code was written in the original file, the task wasn't about fixing types but writing methods
please, correct me if I'm wrong

2023-02-06 09:12 UTC, Dmitrii98 commented on src/app/app.component.ts
> +  areAllValuesTrue(elements: boolean[]): boolean {
fixed

2023-02-06 09:16 UTC, parabolabam commented on src/app/app.component.ts
> +    this.charactersResults$ = this.searchTermByCharacters
no worries, I got it

2023-02-06 09:18 UTC, parabolabam commented on src/app/app.component.ts
> +      this.isLoading = this.areAllValuesTrue([charactersLoading, planetsLoading]);
```suggestion
      this.isLoading$ = combineLatest([
      this.mockDataService.getCharactersLoader(),
      this.mockDataService.getPlanetLoader()
    ]).pipe(
      map((loaders) => this.areAllValuesTrue(loaders))
    )
```

2023-02-06 09:22 UTC, parabolabam commented on src/app/app.component.ts
> +        this.charactersResults$,
first, I mentioned subscribing can be avoided above. But if you have to, then put this subscription into a separate class property.

```suggestion
        readonly subscription: Subscription;
        
        someMethod() {
          this.subscription = combineLatest(...).subscribe(...)
        }
        
        ngOnDestroy() {
          this.subscription.unsubscribe()
        }
```

2023-02-06 09:30 UTC, Dmitrii98 commented on src/app/app.component.ts
> +        this.charactersResults$,
done

2023-02-06 09:34 UTC, Dmitrii98 commented on src/app/app.component.ts
> +      this.isLoading = this.areAllValuesTrue([charactersLoading, planetsLoading]);
got your point, but according to the task I have to implement unsubscribing
anyway I'll take this solution into consideration, thank you

2023-02-06 09:41 UTC, parabolabam commented on src/app/app.component.ts
> +      this.isLoading = this.areAllValuesTrue([charactersLoading, planetsLoading]);
You still can subscribe and unsubscribe from that case, if you need to. It doesn't affect task tremendeuously :)

2023-02-06 15:45 UTC, merged